# Generated by Django 2.0.4 on 2018-05-07 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='inc_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='borrows',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='readers',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
