# Generated by Django 2.0.4 on 2018-05-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookms', '0003_auto_20180507_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow_histry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField()),
                ('return_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookms.Books')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookms.Readers')),
            ],
        ),
    ]
