# Generated by Django 2.0.4 on 2018-05-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookms', '0004_borrow_histry'),
    ]

    operations = [
        migrations.AddField(
            model_name='readers',
            name='delay_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readers',
            name='forbid_date',
            field=models.DateField(null=True),
        ),
    ]
