# Generated by Django 2.0.4 on 2018-05-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookms', '0006_auto_20180518_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='readers',
            name='forbid',
            field=models.BooleanField(default=False),
        ),
    ]
