# Generated by Django 2.0.4 on 2018-05-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookms', '0008_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
