# Generated by Django 2.0.4 on 2018-05-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookms', '0010_ratings_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rate',
            field=models.FloatField(default=None, null=True),
        ),
    ]
