# Generated by Django 2.0.4 on 2018-05-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookms', '0011_auto_20180518_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
